spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/diabeti_control
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: PRAr/+mvYHJwjQiJVwGxMp19poc9zHhPMf0IqBJlHxo=
      expiration: 86400000
      refresh-token:
        expiration: 604800000